/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package principal;

/**
 *
 * @author ASUS
 */
public class mdiPrincipal extends javax.swing.JFrame {

    private jpCuadrado objCuadrado = new jpCuadrado();
    private jpCírculo objCírculo = new jpCírculo();
    private jpRectangulo objRectangulo = new jpRectangulo();
    private jpRombo objRombo = new jpRombo();
    private jpTrapecio objTrapecio = new jpTrapecio();
    private jpTrianguloR objTrianguloR = new jpTrianguloR();
    
    private void inicializarFormularios() {
        // Cuadrado
        jifCuadrado.setContentPane(objCuadrado);
        objCuadrado.setSize(300, 300);
        jifCuadrado.setSize(300, 330);

        // Círculo
        jifCírculo.setContentPane(objCírculo);
        objCírculo.setSize(300, 300);
        jifCírculo.setSize(300, 330);

        // Rectángulo
        jifRectangulo.setContentPane(objRectangulo);
        objRectangulo.setSize(300, 300);
        jifRectangulo.setSize(300, 330);

        // Rombo
        jifRombo.setContentPane(objRombo);
        objRombo.setSize(300, 300);
        jifRombo.setSize(300, 330);

        // Trapecio
        jifTrapecio.setContentPane(objTrapecio);
        objTrapecio.setSize(300, 300);
        jifTrapecio.setSize(300, 330);

        // Triángulo
        jifTrianguloR.setContentPane(objTrianguloR);
        objTrianguloR.setSize(300, 300);
        jifTrianguloR.setSize(300, 330);
    }
    /**
     * Creates new form mdiPrincipal
     */
    public mdiPrincipal() {
        initComponents();
        this.inicializarFormularios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jifCuadrado = new javax.swing.JInternalFrame();
        jifCírculo = new javax.swing.JInternalFrame();
        jifRectangulo = new javax.swing.JInternalFrame();
        jifRombo = new javax.swing.JInternalFrame();
        jifTrapecio = new javax.swing.JInternalFrame();
        jifTrianguloR = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jmiCírculo = new javax.swing.JMenuItem();
        jmiCuadrado = new javax.swing.JMenuItem();
        jmirectangulo = new javax.swing.JMenuItem();
        jmiTrianguloR = new javax.swing.JMenuItem();
        jmiRombo = new javax.swing.JMenuItem();
        jmiTrapecio = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifCuadrado.setClosable(true);
        jifCuadrado.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifCuadrado.setVisible(false);

        javax.swing.GroupLayout jifCuadradoLayout = new javax.swing.GroupLayout(jifCuadrado.getContentPane());
        jifCuadrado.getContentPane().setLayout(jifCuadradoLayout);
        jifCuadradoLayout.setHorizontalGroup(
            jifCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifCuadradoLayout.setVerticalGroup(
            jifCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifCuadrado);
        jifCuadrado.setBounds(10, 10, 160, 150);

        jifCírculo.setClosable(true);
        jifCírculo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifCírculo.setVisible(false);

        javax.swing.GroupLayout jifCírculoLayout = new javax.swing.GroupLayout(jifCírculo.getContentPane());
        jifCírculo.getContentPane().setLayout(jifCírculoLayout);
        jifCírculoLayout.setHorizontalGroup(
            jifCírculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifCírculoLayout.setVerticalGroup(
            jifCírculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifCírculo);
        jifCírculo.setBounds(180, 10, 160, 150);

        jifRectangulo.setClosable(true);
        jifRectangulo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifRectangulo.setVisible(false);

        javax.swing.GroupLayout jifRectanguloLayout = new javax.swing.GroupLayout(jifRectangulo.getContentPane());
        jifRectangulo.getContentPane().setLayout(jifRectanguloLayout);
        jifRectanguloLayout.setHorizontalGroup(
            jifRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifRectanguloLayout.setVerticalGroup(
            jifRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifRectangulo);
        jifRectangulo.setBounds(350, 10, 160, 150);

        jifRombo.setClosable(true);
        jifRombo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifRombo.setVisible(false);

        javax.swing.GroupLayout jifRomboLayout = new javax.swing.GroupLayout(jifRombo.getContentPane());
        jifRombo.getContentPane().setLayout(jifRomboLayout);
        jifRomboLayout.setHorizontalGroup(
            jifRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifRomboLayout.setVerticalGroup(
            jifRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifRombo);
        jifRombo.setBounds(10, 170, 160, 150);

        jifTrapecio.setClosable(true);
        jifTrapecio.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifTrapecio.setVisible(false);

        javax.swing.GroupLayout jifTrapecioLayout = new javax.swing.GroupLayout(jifTrapecio.getContentPane());
        jifTrapecio.getContentPane().setLayout(jifTrapecioLayout);
        jifTrapecioLayout.setHorizontalGroup(
            jifTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifTrapecioLayout.setVerticalGroup(
            jifTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifTrapecio);
        jifTrapecio.setBounds(180, 170, 160, 150);

        jifTrianguloR.setClosable(true);
        jifTrianguloR.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifTrianguloR.setVisible(false);

        javax.swing.GroupLayout jifTrianguloRLayout = new javax.swing.GroupLayout(jifTrianguloR.getContentPane());
        jifTrianguloR.getContentPane().setLayout(jifTrianguloRLayout);
        jifTrianguloRLayout.setHorizontalGroup(
            jifTrianguloRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifTrianguloRLayout.setVerticalGroup(
            jifTrianguloRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifTrianguloR);
        jifTrianguloR.setBounds(350, 170, 160, 150);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        jmiCírculo.setMnemonic('o');
        jmiCírculo.setText("Círculo");
        jmiCírculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCírculoActionPerformed(evt);
            }
        });
        fileMenu.add(jmiCírculo);

        jmiCuadrado.setMnemonic('s');
        jmiCuadrado.setText("Cuadrado");
        jmiCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCuadradoActionPerformed(evt);
            }
        });
        fileMenu.add(jmiCuadrado);

        jmirectangulo.setMnemonic('a');
        jmirectangulo.setText("Rectangulo");
        jmirectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmirectanguloActionPerformed(evt);
            }
        });
        fileMenu.add(jmirectangulo);

        jmiTrianguloR.setText("TrianguloR");
        jmiTrianguloR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTrianguloRActionPerformed(evt);
            }
        });
        fileMenu.add(jmiTrianguloR);

        jmiRombo.setText("Rombo");
        jmiRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRomboActionPerformed(evt);
            }
        });
        fileMenu.add(jmiRombo);

        jmiTrapecio.setText("Trapecio");
        jmiTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTrapecioActionPerformed(evt);
            }
        });
        fileMenu.add(jmiTrapecio);

        jmiSalir.setMnemonic('x');
        jmiSalir.setText("Exit");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        fileMenu.add(jmiSalir);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCírculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCírculoActionPerformed
        // TODO add your handling code here:
        jifCírculo.setVisible(true);
    }//GEN-LAST:event_jmiCírculoActionPerformed

    private void jmiCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCuadradoActionPerformed
        // TODO add your handling code here:
        jifCuadrado.setVisible(true);
    }//GEN-LAST:event_jmiCuadradoActionPerformed

    private void jmirectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmirectanguloActionPerformed
        // TODO add your handling code here:
        jifRectangulo.setVisible(true);
    }//GEN-LAST:event_jmirectanguloActionPerformed

    private void jmiTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTrapecioActionPerformed
        // TODO add your handling code here:
        jifTrapecio.setVisible(true);
    }//GEN-LAST:event_jmiTrapecioActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRomboActionPerformed
        // TODO add your handling code here:
        jifRombo.setVisible(true);
    }//GEN-LAST:event_jmiRomboActionPerformed

    private void jmiTrianguloRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTrianguloRActionPerformed
        // TODO add your handling code here:
        jifTrianguloR.setVisible(true);
        
    }//GEN-LAST:event_jmiTrianguloRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JInternalFrame jifCuadrado;
    private javax.swing.JInternalFrame jifCírculo;
    private javax.swing.JInternalFrame jifRectangulo;
    private javax.swing.JInternalFrame jifRombo;
    private javax.swing.JInternalFrame jifTrapecio;
    private javax.swing.JInternalFrame jifTrianguloR;
    private javax.swing.JMenuItem jmiCuadrado;
    private javax.swing.JMenuItem jmiCírculo;
    private javax.swing.JMenuItem jmiRombo;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiTrapecio;
    private javax.swing.JMenuItem jmiTrianguloR;
    private javax.swing.JMenuItem jmirectangulo;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
